#!/usr/bin/env python3
"""Generate a runtime ROM loader that replaces AppleWin's `apple2roms` target.

AppleWin compiles the Apple II system ROMs into the binary with xxd -i
(resource/CMakeLists.txt -> add_resources). That is what WITH_APPLE_ROMS=ON
builds, and it is why the machine boots out of the box -- but those ROMs are
Apple copyrighted firmware, so an artifact built that way cannot be
redistributed (see COMPLIANCE.md).

WITH_APPLE_ROMS=OFF builds this instead: a translation unit that defines the
same `apple2roms::data` map, but fills it by reading ROM files from the user's
ROM directory at first use. AppleWin's common2 links `apple2roms`
unconditionally, so the target has to exist either way -- it just stops
carrying Apple's bytes.

What stays embedded: AppleWin's own artwork and fonts, plus spoverslip.bin --
the SmartPort-over-SLIP card firmware from the FujiNetWIFI fork, without which
there is no FujiNet. What moves out: every other firmware image.

The id -> filename table is parsed out of AppleWin's own
resource/CMakeLists.txt rather than duplicated here, so it cannot drift from
the tree we actually staged.
"""

import re
import sys
from pathlib import Path

# What "the Apple II system ROMs" means for WITH_APPLE_ROMS=OFF.
#
# The externalised set is the firmware images -- .rom/.ROM/.bin -- which is
# the conservative reading: it covers Apple's own monitor/Applesoft/Disk ][
# /SSC firmware and also the third-party card ROMs (Mockingboard, Mouse,
# ThunderClock, ...) whose redistribution terms we have not established
# either. Everything else AppleWin bundles is its own artwork and fonts and
# stays compiled in.
#
# spoverslip.bin is the one firmware image we keep: it is the
# SmartPort-over-SLIP card from the FujiNetWIFI AppleWin fork, not Apple's,
# and without it there is no FujiNet at all.
EXTERNAL_SUFFIXES = (".rom", ".bin")
ALWAYS_EMBED = {
    "spoverslip.bin",
}


def is_external(filename):
    if filename in ALWAYS_EMBED:
        return False
    return filename.lower().endswith(EXTERNAL_SUFFIXES)


def parse_resources(cmakelists):
    """[(resource_id, filename)] in declaration order."""
    text = cmakelists.read_text(encoding="utf-8", errors="surrogateescape")
    m = re.search(r"add_resources\([^\n]*\n(.*?)\n\s*\)", text, re.S)
    if not m:
        sys.exit("generate-rom-loader.py: could not find add_resources() block")
    out = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = re.match(r'^(\S+)\s+"([^"]+)"\s*$', line)
        if parts:
            out.append((parts.group(1), parts.group(2)))
    if not out:
        sys.exit("generate-rom-loader.py: add_resources() block parsed empty")
    return out


def c_ident(name):
    return re.sub(r"[ ./-]", "_", name)


def main():
    if len(sys.argv) != 5:
        sys.exit("usage: generate-rom-loader.py <resource/CMakeLists.txt> "
                 "<out.cpp> <out.h> <out-embed-list>")
    cmakelists, out_cpp, out_h, out_list = (Path(a) for a in sys.argv[1:])
    resources = parse_resources(cmakelists)

    embed = [(rid, fn) for rid, fn in resources if not is_external(fn)]
    external = [(rid, fn) for rid, fn in resources if is_external(fn)]

    lines = []
    w = lines.append
    w('// GENERATED by tools/applewin/generate-rom-loader.py -- do not edit.')
    w('//')
    w('// Replaces AppleWin\'s apple2roms target for WITH_APPLE_ROMS=OFF: the')
    w('// same apple2roms::data map, filled from ROM files on disk instead of')
    w('// from bytes compiled into the binary. See COMPLIANCE.md.')
    w('')
    w('#include <cstdint>')
    w('#include <cstdio>')
    w('#include <cstdlib>')
    w('#include <map>')
    w('#include <string>')
    w('#include <vector>')
    w('')
    w('#include "../resource/resource.h"')
    w('#include "apple2roms_data.h"')
    w('')
    w('// Embedded (not Apple copyright, and required for the app to work).')
    for _, fn in embed:
        sym = c_ident(fn)
        w(f'extern unsigned char {sym}[];')
        w(f'extern int {sym}_len;')
    w('')
    w('namespace {')
    w('')
    w('struct RomFile { uint32_t id; const char *name; };')
    w('')
    w('// Parsed from AppleWin\'s resource/CMakeLists.txt at build time.')
    w('const RomFile kExternalRoms[] = {')
    for rid, fn in external:
        w(f'    {{ {rid}, "{fn}" }},')
    w('};')
    w('')
    w('// Kept alive for the process lifetime: the map hands out raw pointers.')
    w('std::vector<std::vector<unsigned char>> g_storage;')
    w('')
    w('std::string rom_dir()')
    w('{')
    w('    if (const char *e = std::getenv("APPLE2_ROM_DIR"))')
    w('        if (*e) return e;')
    w('    std::string base;')
    w('    if (const char *x = std::getenv("XDG_DATA_HOME"))')
    w('        if (*x) base = x;')
    w('    if (base.empty()) {')
    w('        const char *home = std::getenv("HOME");')
    w('        if (!home || !*home) return "roms";')
    w('        base = std::string(home) + "/.local/share";')
    w('    }')
    w('    return base + "/fujinet-go-apple2/roms";')
    w('}')
    w('')
    w('bool read_file(const std::string &path, std::vector<unsigned char> &out)')
    w('{')
    w('    std::FILE *f = std::fopen(path.c_str(), "rb");')
    w('    if (!f) return false;')
    w('    std::fseek(f, 0, SEEK_END);')
    w('    const long n = std::ftell(f);')
    w('    std::fseek(f, 0, SEEK_SET);')
    w('    if (n <= 0) { std::fclose(f); return false; }')
    w('    out.resize(static_cast<size_t>(n));')
    w('    const size_t got = std::fread(out.data(), 1, out.size(), f);')
    w('    std::fclose(f);')
    w('    return got == out.size();')
    w('}')
    w('')
    w('std::map<uint32_t, std::pair<const unsigned char *, unsigned int>> load()')
    w('{')
    w('    std::map<uint32_t, std::pair<const unsigned char *, unsigned int>> m;')
    w('')
    for rid, fn in embed:
        sym = c_ident(fn)
        w(f'    m[{rid}] = {{ {sym}, static_cast<unsigned int>({sym}_len) }};')
    w('')
    w('    const std::string dir = rom_dir();')
    w('    g_storage.reserve(sizeof(kExternalRoms) / sizeof(kExternalRoms[0]));')
    w('    int found = 0;')
    w('    for (const RomFile &r : kExternalRoms) {')
    w('        std::vector<unsigned char> buf;')
    w('        if (!read_file(dir + "/" + r.name, buf)) continue;')
    w('        g_storage.push_back(std::move(buf));')
    w('        const std::vector<unsigned char> &held = g_storage.back();')
    w('        m[r.id] = { held.data(), static_cast<unsigned int>(held.size()) };')
    w('        ++found;')
    w('    }')
    w('')
    w('    if (found == 0) {')
    w('        std::fprintf(stderr,')
    w('            "apple2roms: no ROM files in %s -- this build does not embed the\\n"')
    w('            "            Apple II system ROMs (see COMPLIANCE.md). Import them\\n"')
    w('            "            with \\"Import System ROMs...\\" or set APPLE2_ROM_DIR.\\n",')
    w('            dir.c_str());')
    w('    }')
    w('    return m;')
    w('}')
    w('')
    w('} // namespace')
    w('')
    w('namespace apple2roms {')
    w('// Dynamically initialised. GetResourceData() runs during machine init,')
    w('// long after static initialisation, so this is safe.')
    w('const std::map<uint32_t, std::pair<const unsigned char *, unsigned int>> data = load();')
    w('}')
    w('')

    # The same declaration header add_resources() emits; common2 includes it.
    out_h.write_text(
        "#include <map>\n"
        "#include <cstdint>\n"
        "\n"
        "namespace apple2roms\n"
        "{\n"
        "    extern const std::map<uint32_t, std::pair<const unsigned char *, "
        "unsigned int>> data;\n"
        "}\n",
        encoding="utf-8")

    out_cpp.write_text("\n".join(lines), encoding="utf-8")
    out_list.write_text("\n".join(fn for _, fn in embed) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
